### ISSUE TITLE
Why is it not part of the compiler?

### ISSUE THREAD

**Issue by SyrianSpock** [alexkohler/nakedret#16]
This is a very useful check. Why is it not part of the compiler?

**Comment by alexkohler** [comment]
`nakedret` takes the stance that naked returns are generally a source of bugs and take away from the simplicity of reading/writing Go code. That said, naked returns themselves are part of the Go language. There are fairly strong opinions on both sides - I'd encourage you to read https://github.com/golang/go/issues/21291 to see both sides of the argument.
