### ISSUE TITLE
github.com/alexkohler/nakedret is not used in this modulego mod tidy

### ISSUE THREAD

**Issue by raliqala** [alexkohler/nakedret#19]
Hi  

Is it possible to install using ```go install github.com/**********``` because when I use ```go get -u github.com/****``` it saves the package in go.mod then i get this message github.com/alexkohler/nakedret is not used in this modulego mod tidy

Thanks in advanced

**Comment by alexkohler** [comment]
Hey there! Apologies, missed this original issue. I think the best course of action is to just use `go install`, e.g.:
```bash
$ go install github.com/alexkohler/nakedret@latest
go: downloading github.com/alexkohler/nakedret v1.0.0
$ 
```

**Comment by dibrinsofor** [comment]
That's odd! I am unable to reproduce this. what does line 3 do?
>`$ ➡ which nakedret`

**Comment by alexkohler** [comment]
`which nakedret` would tell you the location of the `nakedret` binary if it's on your `PATH`. Are you able to `go install` other binaries?

**Comment by dibrinsofor** [comment]
I see, I had to manually `setx ...` the path on windows to get it to run. I'll setup a pr to update the docs with this first thing in the morning.

**Comment by alexkohler** [comment]
Sounds good, much appreciated!
