### ISSUE TITLE
Tag and release a stable version (1.0?)

### ISSUE THREAD

**Issue by mcandre** [alexkohler/nakedret#2]
Thank you for publishing your wonderfully helpful nakedret system for identifying sensitive Go code! Could we get a git tag and release version, say v1.0, for this project? That way, developers can have confidence that they are using a specific version of nakedret, in case of any future changes that might break backwards compatibility.

**Comment by alexkohler** [comment]
Sure - been meaning to get around to this.

**Comment by alexkohler** [comment]
Hey @mcandre, sorry for the delay - I've tagged v1.0.
