### ISSUE TITLE
Naked returns outside top-level functions are ignored

### ISSUE THREAD

**Issue by rittneje** [alexkohler/nakedret#20]
None of the following naked returns are currently flagged. (For comparison, they are flagged by revive.)

```go
var _ = func() (err error) {
	return
}

func foo() {
	var _ = func() (err error) {
		return
	}

	func() (err error) {
		return
	}()

	defer func() (err error) {
		return
	}()

	go func() (err error) {
		return
	}()
}
```

**Comment by dibrinsofor** [comment]
@alexkohler would you mind walking me through this problem? I would like to take this up or at least attempt it

**Comment by alexkohler** [comment]
hi @dibrinsofor! I'm not exactly what sure needs to be done to support these additional cases, but I imagine we'd just need to further tease apart the AST to identify these additional cases. We currently walk the AST here:
https://github.com/alexkohler/nakedret/blob/b2c01465241327a7db35ec77f94ff19168bcabaa/nakedret.go#L196-L235

I imagine we'd need to add some additional `case`s and potentially some additional logic within the existing cases. You should be able to add these cases into the `testdata/` directory and use the tests under `nakedret_test.go` to validate your changes.

**Comment by dibrinsofor** [comment]
It looks like `nakedret` already identifies these cases, I would just like to extend the unit tests to include them.

would you mind hopping on a call to answer some questions? I want to rewrite the tests but just want to run somethings by you.
