### ISSUE TITLE
v1.0.2 install is broken

### ISSUE THREAD

**Issue by jesusprubio** [alexkohler/nakedret#26]
Error: `package github.com/alexkohler/nakedret is not a main package`

**Comment by alexandear** [comment]
@jesusprubio install command changed in v1.0.2. You should run the following (see [README](https://github.com/alexkohler/nakedret#installation)):
```
go install github.com/alexkohler/nakedret/cmd/nakedret@latest
```

@alexkohler I think the major version should be bumped to v2.0.0.

**Comment by alexkohler** [comment]
@alexandear - ah, you're probably right. Done.

**Comment by zalenskivolt** [comment]
@alexkohler I think v2 requires another small update. see #27
