### ISSUE TITLE
Support for globbing

### ISSUE THREAD

**Issue by lmorg** [alexkohler/nakedret#3]
In your README you state the following TODO:

> Globbing support (e.g. nakedret *.go)

Which can probably be removed as it's already handled by the shell.

A bit of background (apologies if you're already aware; just making sure there is sufficient detail in this post):

On POSIX shells (eg Bash) and other shells that follow similar conventions, globbing is handled by the shell itself rather than the called application. Since you're pulling the array of unflagged parameters via `flag.Args()` your tool already supports globbing on Linux / OS X shells. Windows, as usual, is a whole other edge case - but there is always WSL for that. Or obviously the Golang filesystem library for globbing which you've no doubt already considered. Just make sure you make it's a separate source file with `// +build windows` at the top so you don't break things for us Linux users ;)

**Comment by alexkohler** [comment]
I actually had no idea this was the case! Thank you for submitting the issue - I'll remove that TODO :+1: With respect to Windows users... meh :rofl:
