### ISSUE TITLE
should exit != 0 when it finds something

### ISSUE THREAD

**Issue by dcu** [alexkohler/nakedret#7]
otherwise it's hard to add to a pipeline

**Comment by alexkohler** [comment]
Hey @dcu, thanks for the issue. I completely agree (a lot of my other newer linters now include an `exit_status` flag. In the interim, I'd recommend you use [golangci-lint](https://github.com/golangci/golangci-lint) as a wrapper to `nakedret`. For example: golangci-lint run --issues-exit-code --disable-all --enable=nakedret`

**Comment by dcu** [comment]
we don't use any metalinters but I was able to find a workaround using bash
